# Generated by Django 3.0.8 on 2020-07-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=256)),
                ('site_address', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=256)),
                ('time', models.IntegerField()),
                ('from_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_site_id', to='traveldata.Site')),
                ('to_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_site_id', to='traveldata.Site')),
            ],
        ),
    ]
